version: "3"

networks:
  backend:

volumes:
  pgdata:

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8100:8000" # django
    depends_on:
      - postgres
    volumes:
      - ./web:/app
    networks:
      - backend
    env_file: .env
    command: ./bootup.sh

  postgres:
    restart: always
    image: postgres:13.3
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - backend
