FROM python:3.11.6

RUN pip install --upgrade pip
RUN pip install Django==4.2.7
RUN pip install django-extensions==3.2.3
RUN pip install psycopg2-binary==2.9.9
RUN pip install django-cors-headers==4.3.1
RUN pip install requests==2.31.0
RUN pip install ipython==8.18.1

WORKDIR /app
